#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 61
#define YY_END_OF_BUFFER 62
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[713] =
    {   0,
       62,   60,   61,   12,   60,   61,   10,   61,   60,   61,
       60,   61,   60,   61,   60,   61,   58,   60,   61,   60,
       61,   49,   60,   61,   50,   60,   61,   41,   60,   61,
       39,   60,   61,   51,   60,   61,   40,   60,   61,   60,
       61,   42,   60,   61,   35,   60,   61,   52,   60,   61,
       47,   60,   61,   38,   60,   61,   45,   60,   61,   11,
       31,   32,   60,   61,   11,   31,   32,   60,   61,   11,
       31,   32,   60,   61,   11,   31,   32,   60,   61,   53,
       60,   61,   54,   60,   61,   11,   32,   60,   61,   11,
       32,   60,   61,   11,   32,   60,   61,   11,   32,   60,

       61,   11,   32,   60,   61,   11,   32,   60,   61,   11,
       32,   60,   61,   11,   32,   60,   61,   11,   32,   60,
       61,   11,   32,   60,   61,   11,   32,   60,   61,   11,
       32,   60,   61,   11,   32,   60,   61,    9,   60,   61,
        8,   12,   60,   61,    5,   10,   61,    9,   60,   61,
        9,   60,   61,    9,   60,   61,    9,   60,   61,    9,
       58,   60,   61,    9,   60,   61,    9,   49,   60,   61,
        9,   50,   60,   61,    9,   41,   60,   61,    9,   39,
       60,   61,    9,   51,   60,   61,    9,   40,   60,   61,
        9,   60,   61,    9,   42,   60,   61,    9,   35,   60,

       61,    9,   52,   60,   61,    9,   47,   60,   61,    9,
       38,   60,   61,    9,   45,   60,   61,    9,   11,   31,
       32,   60,   61,    9,   11,   31,   32,   60,   61,    9,
       11,   31,   32,   60,   61,    9,   11,   31,   32,   60,
       61,    9,   53,   60,   61,    9,   54,   60,   61,    9,
       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,
       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,
       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,
       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,
       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,

       11,   32,   60,   61,    9,   11,   32,   60,   61,    9,
       11,   32,   60,   61,    4,   61,    3,   61,    4,   61,
       10,   44,    7,   55,   35,   57,   33,   34,   48,   43,
       46,   11,   31,   32,   11,   32,   11,   32,   11,   32,
       11,   32,   11,   32,   11,   32,   11,   32,   11,   32,
       11,   32,   11,   32,   11,   19,   32,   11,   27,   32,
       11,   32,   11,   21,   32,   11,   32,   11,   32,   11,
       32,   11,   32,    9,    8,    5,    5,   10,    9,   44,
        9,    9,    9,    6,    7,    9,    9,    9,   55,    9,
        9,   35,    9,   57,    9,   33,   34,    9,   48,    9,

       43,    9,   46,    9,   11,   31,   32,    9,   11,   32,
        9,   11,   32,    9,   11,   32,    9,   11,   32,    9,
       11,   32,    9,   11,   32,    9,   11,   32,    9,   11,
       32,    9,   11,   32,    9,   11,   32,    9,   11,   19,
       32,    9,   11,   27,   32,    9,   11,   32,    9,   11,
       21,   32,    9,   11,   32,    9,   11,   32,    9,   11,
       32,    9,   11,   32,   36,    1,   37,   33,   34,   11,
       32,   11,   32,   11,   32,   11,   13,   32,   11,   32,
       11,   32,   11,   15,   29,   32,   11,   32,   11,   32,
       11,   18,   26,   32,   11,   20,   32,   11,   32,   11,

       32,   11,   32,   11,   32,    6,    9,   36,    1,    9,
        9,   37,    9,   33,   34,    9,   11,   32,    9,   11,
       32,    9,   11,   32,    9,   11,   13,   32,    9,   11,
       32,    9,   11,   32,    9,   11,   15,   29,   32,    9,
       11,   32,    9,   11,   32,    9,   11,   18,   26,   32,
        9,   11,   20,   32,    9,   11,   32,    9,   11,   32,
        9,   11,   32,    9,   11,   32,    2,   33,   34,   11,
       32,   11,   32,   59,   11,   24,   32,   11,   32,   11,
       32,   11,   16,   32,   11,   17,   32,   11,   32,   11,
       32,   11,   32,   11,   32,    9,   33,   34,    9,   11,

       32,    9,   11,   32,   59,    9,   11,   24,   32,    9,
       11,   32,    9,   11,   32,    9,   11,   16,   32,    9,
       11,   17,   32,    9,   11,   32,    9,   11,   32,    9,
       11,   32,    9,   11,   32,   33,   34,   11,   25,   32,
       11,   14,   32,   11,   32,   56,   11,   30,   32,   11,
       28,   32,   11,   32,   11,   23,   32,    9,   33,   34,
        9,   11,   25,   32,    9,   11,   14,   32,    9,   11,
       32,   56,    9,   11,   30,   32,    9,   11,   28,   32,
        9,   11,   32,    9,   11,   23,   32,   33,   34,   11,
       22,   32,    9,   33,   34,    9,   11,   22,   32,   33,

       34,    9,   33,   34,   33,   34,    9,   33,   34,   34,
        9,   34
    } ;

static const flex_int16_t yy_accept[262] =
    {   0,
        1,    1,    1,    1,    1,    2,    4,    7,    9,   11,
       13,   15,   17,   20,   22,   25,   28,   31,   34,   37,
       40,   42,   45,   48,   51,   54,   57,   60,   65,   70,
       75,   80,   83,   86,   90,   94,   98,  102,  106,  110,
      114,  118,  122,  126,  130,  134,  138,  141,  145,  148,
      151,  154,  157,  160,  164,  167,  171,  175,  179,  183,
      187,  191,  194,  198,  202,  206,  210,  214,  218,  224,
      230,  236,  242,  246,  250,  255,  260,  265,  270,  275,
      280,  285,  290,  295,  300,  305,  310,  315,  317,  319,
      321,  322,  323,  323,  323,  323,  324,  324,  325,  325,

      326,  327,  329,  330,  331,  332,  335,  337,  339,  341,
      343,  345,  347,  349,  351,  353,  355,  358,  361,  363,
      366,  368,  370,  372,  374,  375,  376,  377,  377,  377,
      379,  381,  382,  383,  384,  384,  386,  387,  388,  390,
      391,  393,  395,  398,  400,  402,  404,  408,  411,  414,
      417,  420,  423,  426,  429,  432,  435,  438,  442,  446,
      449,  453,  456,  459,  462,  465,  465,  466,  467,  468,
      470,  472,  474,  476,  479,  481,  483,  487,  489,  491,
      495,  498,  500,  502,  504,  506,  506,  507,  507,  509,
      511,  511,  513,  516,  519,  522,  525,  529,  532,  535,

      540,  543,  546,  551,  555,  558,  561,  564,  567,  568,
      570,  572,  575,  578,  580,  582,  585,  588,  590,  592,
      594,  596,  599,  602,  606,  610,  613,  616,  620,  624,
      627,  630,  633,  636,  638,  641,  644,  647,  650,  653,
      655,  658,  661,  665,  669,  673,  677,  681,  684,  688,
      690,  693,  696,  700,  702,  705,  707,  710,  711,  713,
      713
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,    1,   20,
       21,   22,    1,    1,   23,   23,   23,   23,   23,   24,
       23,   23,   23,   23,   23,   23,   23,   25,   23,   23,
       23,   23,   23,   26,   23,   23,   23,   23,   23,   23,
       27,    1,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   39,   42,
       43,   44,   39,   45,   46,   47,   48,   39,   49,   39,
       39,   39,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[50] =
    {   0,
        1,    2,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    4,    4,    4,    4,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[272] =
    {   0,
        0,   49,   96,   97,  474,  955,  955,  955,  470,  444,
      458,  460,  955,    0,  955,  955,  448,  955,  955,   88,
      437,  955,   89,  955,  433,  432,  431,   90,   99,   88,
       81,  955,  955,    0,  407,  403,  406,  412,  404,  400,
       85,  399,  392,  389,  100,  390,    0,  133,  955,  423,
      404,  136,  141,    0,  144,    0,    0,  410,    0,    0,
      132,  403,    0,  133,    0,  394,  393,  392,  154,  380,
      366,  363,    0,    0,  186,  195,  204,  216,  229,  241,
      250,  276,  260,  290,  299,  327,  340,  955,  955,  400,
      955,  955,  399,  393,  395,  955,  386,  955,  371,  189,

      955,  370,  955,  955,  955,  355,    0,  339,  337,  323,
      337,  334,  332,  325,   63,  314,    0,    0,  308,    0,
      316,  307,  301,  309,    0,  288,  955,  343,  129,  955,
        0,  229,  337,  258,  153,  955,  294,  333,    0,  323,
      190,    0,  322,    0,    0,    0,    0,  308,  349,  358,
      368,  378,  394,  406,  415,  433,  443,  452,  466,  475,
      484,  494,  510,  519,  531,  333,  955,  955,  955,  320,
      290,  296,  295,    0,  297,  275,    0,  285,  278,    0,
        0,  268,  273,  259,  265,  213,  955,  222,    0,    0,
      240,    0,  286,  547,  556,  571,  583,  592,  601,  610,

      619,  632,  644,  653,  662,  671,  685,  694,  955,  270,
      253,    0,    0,  241,  234,    0,    0,  230,  238,  226,
      235,  238,  703,  716,  725,  734,  743,  752,  761,  770,
      779,  796,  805,  233,    0,    0,    0,    0,    0,  208,
        0,  230,  819,  828,  837,  846,  855,  864,  873,  228,
        0,  220,  885,  218,  205,  196,  134,  123,  103,  955,
      914,  918,  922,  926,  108,  930,  934,  938,  942,  946,
      950
    } ;

static const flex_int16_t yy_def[272] =
    {   0,
      260,  260,  261,  261,  260,  260,  260,  260,  260,  260,
      262,  263,  260,  264,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  265,  265,   29,
       29,  260,  260,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  266,  260,  260,  266,
      266,  267,  268,  266,  269,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  260,   69,
       69,   69,  266,  266,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,  260,  260,  260,
      260,  260,  262,  260,  263,  260,  260,  260,  260,  260,

      260,  260,  260,  260,  260,   29,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  266,  260,  260,  260,  270,  260,
      266,  267,  266,  268,  271,  260,  268,  266,  266,  266,
      266,  266,  266,  266,  266,  266,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,  260,  260,  260,  260,  260,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  270,  260,  270,  266,  266,
      271,  266,  266,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   69,   69,   69,   69,   69,  260,  260,
      265,  265,  265,  265,  265,  265,  265,  265,  265,  265,
      265,  266,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,  260,  265,  265,  265,  265,  265,  265,
      265,  266,   69,   69,   69,   69,   69,   69,   69,  260,
      265,  266,   69,  260,  266,  260,  266,  260,  266,    0,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260
    } ;

static const flex_int16_t yy_nxt[1005] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   34,   34,   41,   34,   34,
       34,   42,   43,   44,   45,   34,   34,   34,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
       78,   79,   80,   81,   75,   75,   82,   75,   75,   75,
       83,   84,   85,   86,   75,   75,   75,   87,   89,   89,

      178,   90,   90,   99,   99,  100,  100,  106,  179,  101,
      107,  107,  106,  106,  106,  106,  106,  107,  106,  117,
      259,  106,  106,  106,  106,  110,  118,  106,  108,  122,
      109,  187,  188,  123,  126,  127,  128,   93,   93,  129,
      258,  133,  135,  136,  137,   97,   97,  140,  140,  141,
      141,  259,  125,  142,  125,  136,  191,  125,  125,  125,
      125,  125,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  147,  125,  125,  125,  125,  147,  147,  147,  147,
      125,  125,  147,  148,  148,  148,  148,  148,  148,  148,
      148,  148,  148,  148,  148,  148,  148,  148,  148,  148,

      148,  148,  148,  148,   99,  140,  100,  141,  148,  148,
      148,  148,  148,  258,  148,  187,  188,  148,  148,  148,
      148,  148,  257,  148,  187,  188,  148,  148,  148,  148,
       93,   93,  148,  148,  189,  256,  152,  255,  148,  148,
      148,  148,  136,  191,  148,  254,  148,  252,  153,  251,
      250,  148,  148,  148,  148,  242,  154,  148,  148,  135,
      136,  137,  155,  148,  148,  148,  148,  148,  241,  148,
      240,  239,  148,  148,  148,  148,  238,  148,  148,  237,
      236,  156,  148,  148,  148,  148,  235,  234,  148,  126,
      127,  128,  157,  148,  129,  135,  136,  137,  148,  148,

      148,  148,  160,  222,  148,  221,  220,  148,  219,  218,
      158,  217,  148,  148,  148,  148,  148,  159,  148,  216,
      215,  148,  148,  148,  148,  148,  214,  148,  213,  212,
      148,  148,  148,  148,  161,  211,  148,  210,  209,  193,
      143,  192,  190,  162,  148,  127,  185,  184,  183,  148,
      148,  148,  148,  182,  181,  148,  163,  148,  180,  177,
      164,  176,  148,  148,  148,  148,  148,  175,  148,  174,
      173,  148,  148,  148,  148,  148,  165,  148,  172,  171,
      148,  148,  148,  148,  107,  148,  148,  170,  102,  194,
      148,  148,  148,  148,  169,  148,  148,   96,  168,  195,

      148,  148,  148,  148,  167,  166,  148,  151,  150,  149,
      197,  148,  146,  145,  144,  196,  148,  148,  148,  148,
      143,  139,  148,  148,  131,  130,  124,  198,  148,  148,
      148,  148,  148,  121,  148,  199,  120,  148,  148,  148,
      148,  119,  116,  148,  115,  114,  113,  112,  111,  200,
      148,  105,  104,  103,  102,  148,  148,  148,  148,   98,
      148,  148,   96,   94,   92,  148,  148,  148,  148,  148,
      201,  148,   91,  260,  148,  148,  148,  148,  202,  260,
      148,  260,  260,  148,  260,  260,  260,  203,  148,  148,
      148,  148,  148,  260,  148,  260,  260,  148,  148,  148,

      148,  148,  260,  148,  260,  260,  148,  148,  148,  148,
      260,  148,  148,  260,  260,  260,  148,  148,  148,  148,
      260,  204,  148,  260,  260,  260,  260,  148,  260,  260,
      260,  205,  148,  148,  148,  148,  148,  260,  148,  260,
      260,  148,  148,  148,  148,  260,  260,  148,  148,  260,
      260,  206,  260,  148,  148,  148,  148,  260,  260,  148,
      260,  260,  260,  260,  148,  207,  260,  260,  208,  148,
      148,  148,  148,  148,  260,  148,  260,  260,  148,  148,
      148,  148,  260,  260,  148,  260,  260,  260,  148,  224,
      260,  260,  223,  148,  148,  148,  148,  260,  260,  148,

      148,  260,  260,  260,  225,  148,  148,  148,  148,  148,
      260,  148,  260,  260,  148,  148,  148,  148,  148,  260,
      148,  226,  260,  148,  148,  148,  148,  148,  260,  148,
      260,  260,  148,  148,  148,  148,  148,  260,  148,  260,
      260,  148,  148,  148,  148,  260,  227,  148,  260,  148,
      260,  260,  260,  228,  148,  148,  148,  148,  260,  260,
      148,  148,  260,  260,  260,  229,  148,  148,  148,  148,
      148,  260,  148,  260,  260,  148,  148,  148,  148,  148,
      260,  148,  260,  260,  148,  148,  148,  148,  148,  260,
      148,  260,  260,  148,  148,  148,  148,  260,  260,  148,

      260,  260,  148,  230,  260,  260,  231,  148,  148,  148,
      148,  148,  260,  148,  260,  260,  148,  148,  148,  148,
      148,  260,  148,  260,  260,  148,  148,  148,  148,  260,
      260,  148,  232,  148,  233,  260,  243,  260,  148,  148,
      148,  148,  148,  260,  148,  260,  260,  148,  148,  148,
      148,  148,  260,  148,  260,  260,  148,  148,  148,  148,
      148,  260,  148,  260,  260,  148,  148,  148,  148,  148,
      260,  148,  260,  244,  148,  148,  148,  148,  148,  260,
      148,  260,  260,  148,  148,  148,  148,  148,  245,  148,
      260,  260,  148,  148,  148,  148,  148,  260,  148,  260,

      260,  148,  148,  148,  148,  260,  260,  148,  260,  260,
      260,  260,  247,  148,  260,  260,  246,  260,  148,  148,
      148,  148,  148,  260,  148,  260,  260,  148,  148,  148,
      148,  260,  260,  148,  260,  260,  148,  260,  249,  260,
      248,  148,  148,  148,  148,  148,  260,  148,  260,  260,
      148,  148,  148,  148,  148,  260,  148,  260,  260,  148,
      148,  148,  148,  148,  260,  148,  260,  260,  148,  148,
      148,  148,  148,  260,  148,  260,  260,  148,  148,  148,
      148,  148,  260,  148,  260,  260,  148,  148,  148,  148,
      148,  260,  148,  260,  260,  148,  148,  148,  148,  260,

      260,  148,  148,  260,  260,  253,  260,  148,  148,  148,
      148,  260,  260,  148,   88,   88,   88,   88,   93,   93,
       93,   93,   95,   95,   95,   95,   97,   97,  260,   97,
      125,  260,  125,  125,  132,  132,  132,  132,  134,  134,
      134,  134,  138,  138,  138,  138,  186,  186,  186,  186,
      135,  135,  135,  135,    5,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260
    } ;

static const flex_int16_t yy_chk[1005] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    3,    4,

      115,    3,    4,   20,   23,   20,   23,   28,  115,   20,
       31,  265,   28,   28,   28,   28,   29,   30,   28,   41,
      259,   29,   29,   29,   29,   31,   41,   29,   29,   45,
       30,  129,  129,   45,   48,   48,   48,   52,   52,   48,
      258,   52,   53,   53,   53,   55,   55,   61,   64,   61,
       64,  257,   55,   61,   69,  135,  135,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,

       69,   69,   69,   75,  100,  141,  100,  141,   75,   75,
       75,   75,   76,  256,   75,  186,  186,   76,   76,   76,
       76,   77,  255,   76,  188,  188,   77,   77,   77,   77,
      132,  132,   77,   78,  132,  254,   76,  252,   78,   78,
       78,   78,  191,  191,   78,  250,   79,  242,   77,  240,
      234,   79,   79,   79,   79,  222,   78,   79,   80,  134,
      134,  134,   79,   80,   80,   80,   80,   81,  221,   80,
      220,  219,   81,   81,   81,   81,  218,   83,   81,  215,
      214,   80,   83,   83,   83,   83,  211,  210,   83,  126,
      126,  126,   81,   82,  126,  137,  137,  137,   82,   82,

       82,   82,   83,  193,   82,  185,  184,   84,  183,  182,
       82,  179,   84,   84,   84,   84,   85,   82,   84,  178,
      176,   85,   85,   85,   85,  148,  175,   85,  173,  172,
      148,  148,  148,  148,   84,  171,  148,  170,  166,  143,
      140,  138,  133,   85,   86,  128,  124,  123,  122,   86,
       86,   86,   86,  121,  119,   86,   86,   87,  116,  114,
       86,  113,   87,   87,   87,   87,  149,  112,   87,  111,
      110,  149,  149,  149,  149,  150,   87,  149,  109,  108,
      150,  150,  150,  150,  106,  151,  150,  102,   99,  149,
      151,  151,  151,  151,   97,  152,  151,   95,   94,  150,

      152,  152,  152,  152,   93,   90,  152,   72,   71,   70,
      152,  153,   68,   67,   66,  151,  153,  153,  153,  153,
       62,   58,  153,  154,   51,   50,   46,  153,  154,  154,
      154,  154,  155,   44,  154,  154,   43,  155,  155,  155,
      155,   42,   40,  155,   39,   38,   37,   36,   35,  155,
      156,   27,   26,   25,   21,  156,  156,  156,  156,   17,
      157,  156,   12,   11,   10,  157,  157,  157,  157,  158,
      156,  157,    9,    5,  158,  158,  158,  158,  156,    0,
      158,    0,    0,  159,    0,    0,    0,  157,  159,  159,
      159,  159,  160,    0,  159,    0,    0,  160,  160,  160,

      160,  161,    0,  160,    0,    0,  161,  161,  161,  161,
        0,  162,  161,    0,    0,    0,  162,  162,  162,  162,
        0,  160,  162,    0,    0,    0,    0,  163,    0,    0,
        0,  162,  163,  163,  163,  163,  164,    0,  163,    0,
        0,  164,  164,  164,  164,    0,    0,  164,  165,    0,
        0,  163,    0,  165,  165,  165,  165,    0,    0,  165,
        0,    0,    0,    0,  194,  164,    0,    0,  165,  194,
      194,  194,  194,  195,    0,  194,    0,    0,  195,  195,
      195,  195,    0,    0,  195,    0,    0,    0,  196,  195,
        0,    0,  194,  196,  196,  196,  196,    0,    0,  196,

      197,    0,    0,    0,  196,  197,  197,  197,  197,  198,
        0,  197,    0,    0,  198,  198,  198,  198,  199,    0,
      198,  198,    0,  199,  199,  199,  199,  200,    0,  199,
        0,    0,  200,  200,  200,  200,  201,    0,  200,    0,
        0,  201,  201,  201,  201,    0,  199,  201,    0,  202,
        0,    0,    0,  201,  202,  202,  202,  202,    0,    0,
      202,  203,    0,    0,    0,  202,  203,  203,  203,  203,
      204,    0,  203,    0,    0,  204,  204,  204,  204,  205,
        0,  204,    0,    0,  205,  205,  205,  205,  206,    0,
      205,    0,    0,  206,  206,  206,  206,    0,    0,  206,

        0,    0,  207,  205,    0,    0,  206,  207,  207,  207,
      207,  208,    0,  207,    0,    0,  208,  208,  208,  208,
      223,    0,  208,    0,    0,  223,  223,  223,  223,    0,
        0,  223,  207,  224,  208,    0,  223,    0,  224,  224,
      224,  224,  225,    0,  224,    0,    0,  225,  225,  225,
      225,  226,    0,  225,    0,    0,  226,  226,  226,  226,
      227,    0,  226,    0,    0,  227,  227,  227,  227,  228,
        0,  227,    0,  226,  228,  228,  228,  228,  229,    0,
      228,    0,    0,  229,  229,  229,  229,  230,  227,  229,
        0,    0,  230,  230,  230,  230,  231,    0,  230,    0,

        0,  231,  231,  231,  231,    0,    0,  231,    0,    0,
        0,    0,  231,  232,    0,    0,  230,    0,  232,  232,
      232,  232,  233,    0,  232,    0,    0,  233,  233,  233,
      233,    0,    0,  233,    0,    0,  243,    0,  233,    0,
      232,  243,  243,  243,  243,  244,    0,  243,    0,    0,
      244,  244,  244,  244,  245,    0,  244,    0,    0,  245,
      245,  245,  245,  246,    0,  245,    0,    0,  246,  246,
      246,  246,  247,    0,  246,    0,    0,  247,  247,  247,
      247,  248,    0,  247,    0,    0,  248,  248,  248,  248,
      249,    0,  248,    0,    0,  249,  249,  249,  249,    0,

        0,  249,  253,    0,    0,  248,    0,  253,  253,  253,
      253,    0,    0,  253,  261,  261,  261,  261,  262,  262,
      262,  262,  263,  263,  263,  263,  264,  264,    0,  264,
      266,    0,  266,  266,  267,  267,  267,  267,  268,  268,
      268,  268,  269,  269,  269,  269,  270,  270,  270,  270,
      271,  271,  271,  271,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,  260
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[62] =
    {   0,
0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
/* 
Basado en la documentacion: https://docs.python.org/3/reference/lexical_analysis.html#

Python Keywords:
False      await      else       import     pass
None       break      except     in         raise
True       class      finally    is         return
and        continue   for        lambda     try
as         def        from       nonlocal   while
assert     del        global     not        with
async      elif       if         or         yield

Python Operators:
+       -       *       **      /       //      %      @
<<      >>      &       |       ^       ~       :=
<       >       <=      >=      ==      !=

*/
#line 21 "scanner.l"
#include <iostream>
#include <stack>
#include <cstdlib>
#include <string.h>
#include "parser.hpp"
extern YYSTYPE yylval;


int comment_start_line;
std::stack<int> _indent_stack;
#line 898 "scanner.cpp"

#line 900 "scanner.cpp"

#define INITIAL 0
#define COMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 38 "scanner.l"



#line 42 "scanner.l"
  /**/
  if (_indent_stack.empty()) {
    _indent_stack.push(0);
  }


#line 1138 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 261 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 955 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

goto find_rule; /* Shut up GCC warning -Wall */
find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 48 "scanner.l"
{ BEGIN(COMMENT); comment_start_line = yylineno; }
	YY_BREAK

case 2:
YY_RULE_SETUP
#line 51 "scanner.l"
{ BEGIN(INITIAL); } // Fin del comentario
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 52 "scanner.l"
{ /* Ignorar saltos de línea dentro del comentario */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 53 "scanner.l"
{ /* Ignorar cualquier otro carácter dentro del comentario */ }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 54 "scanner.l"
{ 
                   std::cerr << "Error: Comentario multilínea sin cerrar. Iniciado en la línea " 
                             << comment_start_line << std::endl;
                   yyterminate();
                 }
	YY_BREAK

case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 61 "scanner.l"
{ /* Ignoramos lineas en blanco */ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 62 "scanner.l"
{ /* Ignoramos comentarios en una linea fisica */ }
	YY_BREAK
case 7:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 63 "scanner.l"
{ /* Ignoramos comentarios que estan dps de un statement */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "scanner.l"
{
              /**/
              if (_indent_stack.top() < yyleng) {
                /**/
                //std::cout << "INDENT" << std::endl;
                _indent_stack.push(yyleng);
                yylval.token = INDENT; return INDENT;
              } else {
                /**/
                while (!_indent_stack.empty() && _indent_stack.top() != yyleng) {
                  _indent_stack.pop();
                  //std::cout << "DEDENT" << std::endl;
                  yylval.token = DEDENT; return DEDENT;
                }

                /**/
                if (_indent_stack.empty()) {
                  std::cerr << "Error: Incorrect indentation on line "
                    << yylineno << std::endl;
                  return 1;
                  exit(1);
                }
              }
            }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "scanner.l"
{
              /**/
              while(_indent_stack.top() != 0) {
                _indent_stack.pop();
                //std::cout << "DEDENT" << std::endl;
                yylval.token = DEDENT; return DEDENT;
              }
              REJECT;
            }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 101 "scanner.l"
{
                yylval.token = NEWLINE; return NEWLINE;
                //std::cout << "NEWLINE" << std::endl;
            }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 106 "scanner.l"
{
              /**/
              while(_indent_stack.top() != 0) {
                _indent_stack.pop();
                //std::cout << "DEDENT" << std::endl;
                yylval.token = DEDENT; return DEDENT;
              }
              return ENDMARKER;
            }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 115 "scanner.l"
{ yylval.str = new std::string(yytext, yyleng); return NAME; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 117 "scanner.l"
{ /* Ignoramos espacios blancos que no sean los de arriba */ }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 119 "scanner.l"
{ yylval.token = AND; return AND; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "scanner.l"
{ yylval.token = BREAK; return BREAK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "scanner.l"
{ yylval.token = DEF; return DEF; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "scanner.l"
{ yylval.token = ELIF; return ELIF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 123 "scanner.l"
{ yylval.token = ELSE; return ELSE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 124 "scanner.l"
{ yylval.token = FOR; return FOR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 125 "scanner.l"
{ yylval.token = IF; return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 126 "scanner.l"
{ yylval.token = NOT; return NOT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "scanner.l"
{ yylval.token = OR; return OR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 128 "scanner.l"
{ yylval.token = RETURN; return RETURN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 129 "scanner.l"
{ yylval.token = WHILE; return WHILE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 130 "scanner.l"
{ yylval.str = new std::string("true"); return BOOLEAN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 131 "scanner.l"
{ yylval.str = new std::string("false"); return BOOLEAN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 132 "scanner.l"
{ yylval.token = FOR; return FOR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 133 "scanner.l"
{ yylval.token = IN; return IN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "scanner.l"
{ yylval.token = RANGE; return RANGE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 135 "scanner.l"
{ yylval.token = DEF; return DEF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 136 "scanner.l"
{ yylval.token = PRINT; return PRINT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 138 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                          return CONSTANT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 141 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                        return IDENTIFIER;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 144 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                        return FLOAT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 147 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                        return DOUBLE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 150 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                        return INTEGER;}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 153 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                        return STRING;}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 156 "scanner.l"
{yylval.str = new std::string(yytext, yyleng);
                              return CHAR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 159 "scanner.l"
{ yylval.token = EQUALS; return EQUALS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 160 "scanner.l"
{ yylval.token = PLUS; return PLUS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 161 "scanner.l"
{ yylval.token = MINUS; return MINUS; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 162 "scanner.l"
{ yylval.token = TIMES; return TIMES; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 163 "scanner.l"
{ yylval.token = DIVIDEDBY; return DIVIDEDBY; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 164 "scanner.l"
{ yylval.token = EQ; return EQ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 165 "scanner.l"
{ yylval.token = NEQ; return NEQ; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 166 "scanner.l"
{ yylval.token = GT; return GT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 167 "scanner.l"
{ yylval.token = GTE; return GTE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 168 "scanner.l"
{ yylval.token = LT; return LT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 169 "scanner.l"
{ yylval.token = LTE; return LTE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 170 "scanner.l"
{ yylval.token = LPAREN; return LPAREN; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 171 "scanner.l"
{ yylval.token = RPAREN; return RPAREN; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 172 "scanner.l"
{ yylval.token = COMMA; return COMMA; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 173 "scanner.l"
{ yylval.token = COLON; return COLON; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 174 "scanner.l"
{ yylval.token = LBRACK; return LBRACK; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 175 "scanner.l"
{ yylval.token = RBRACK; return RBRACK; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 176 "scanner.l"
{ yylval.token = POW; return POW; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 177 "scanner.l"
{ yylval.token = CLASS; return CLASS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 178 "scanner.l"
{ yylval.token = ARROW; return ARROW; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 179 "scanner.l"
{ yylval.token= MOD; return MOD; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 180 "scanner.l"
{ yylval.token = NONE; return NONE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 181 "scanner.l"
{ yylval.token = UNKNOWN; return UNKNOWN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 183 "scanner.l"
ECHO;
	YY_BREAK
#line 1589 "scanner.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 261 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 261 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 260);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 183 "scanner.l"

